"""Added inspiration field to the recipe table

Revision ID: c9c396a5fb2d
Revises: 
Create Date: 2017-04-05 16:19:21.071583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c396a5fb2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('attendence')
    op.drop_table('students')
    op.drop_table('timetable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('day', sa.VARCHAR(), nullable=True),
    sa.Column('time', sa.VARCHAR(), nullable=True),
    sa.Column('branch_code', sa.VARCHAR(), nullable=True),
    sa.Column('time_created', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], [u'course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rollno', sa.VARCHAR(length=250), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.Column('time_created', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('present', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('timetable_id', sa.INTEGER(), nullable=True),
    sa.Column('time_created', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['timetable_id'], [u'timetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=250), nullable=True),
    sa.Column('course_name_long', sa.VARCHAR(), nullable=True),
    sa.Column('course_name_short', sa.VARCHAR(), nullable=True),
    sa.Column('time_created', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('year', sa.VARCHAR(), nullable=True),
    sa.Column('branch', sa.VARCHAR(), nullable=True),
    sa.Column('semester', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
